spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: order-route
          uri: lb:service-order
          predicates:
            - Path=api/order/**
        - id: order-product
          uri: lb:service-product
          predicates:
            - Path=api/product/**
      default-filters:
        -AddResponseHeader=X-HD,123
server:
  port: 8000
